### ISSUE TITLE
Broken on python 3.8

### ISSUE THREAD

**Issue by MegaBluejay** [alecthomas/pawk#16]
Pawk crashes with, as far as I can tell, any pattern and expression if running on python 3.8.
```
~/pawk >>> echo '1 1' | python3.7 pawk 'f[0]'                                                ±[●][master]
1
~/pawk >>> echo '1 1' | python3.8 pawk 'f[0]'                                                ±[●][master]
Traceback (most recent call last):
  File "pawk", line 5, in <module>
    main()
  File "/home/archer/pawk/pawk.py", line 246, in main
    run(sys.argv, sys.stdin, sys.stdout)
  File "/home/archer/pawk/pawk.py", line 233, in run
    actions = [Action.from_options(options, arg) for arg in args]
  File "/home/archer/pawk/pawk.py", line 233, in <listcomp>
    actions = [Action.from_options(options, arg) for arg in args]
  File "/home/archer/pawk/pawk.py", line 88, in from_options
    return cls(pattern=pattern, cmd=cmd, have_end_statement=(options.end is not None), negate=negate, strict=options.strict)
  File "/home/archer/pawk/pawk.py", line 83, in __init__
    self._compile(have_end_statement)
  File "/home/archer/pawk/pawk.py", line 96, in _compile
    self._codeobj = compile_command(self.cmd)
  File "/home/archer/pawk/pawk.py", line 65, in compile_command
    return compile(tree, 'EXPR', 'exec')
ValueError: Name node can't be used with 'None' constant
```

**Comment by SpotlightKid** [comment]
This fixes it for me:

```diff
diff --git a/pawk.py b/pawk.py
index 7c507ee..33e8675 100644
--- a/pawk.py
+++ b/pawk.py
@@ -53,7 +53,7 @@ def save_last_expression(tree, var_name=RESULT_VAR_NAME):
     body = tree.body
     node = body[-1] if len(body) else None
     body.insert(0, ast.Assign(targets=[ast.Name(id=var_name, ctx=ast.Store())],
-                              value=ast.Name(id="None", ctx=ast.Load())))
+                              value=ast.Constant(None)))
     if node and isinstance(node, ast.Expr):
         body[-1] = ast.copy_location(ast.Assign(
             targets=[ast.Name(id=var_name, ctx=ast.Store())], value=node.value), node)
```
