### ISSUE TITLE
Re-release to PyPI with #16 ?

### ISSUE THREAD

**Issue by jrjsmrtn** [alecthomas/pawk#21]
The pawk version on PyPI doesn't include #16 and, unfortunately, doesn't work out of the box with Python 3.8-3.10.

**Comment by alecthomas** [comment]
I'd like to, but I just sunk an hour into getting uploads working and it's too much effort, sorry. PyPI no longer supports setuptools directly uploading via `python setup.py sdist upload` and the new approach fails with this unhelpful message:

```
python3 -m build                                                                                                                                                                            master
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0)
* Getting build dependencies for sdist...
Traceback (most recent call last):
  File "/Users/aat/Projects/pawk/.hermit/python/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Users/aat/Projects/pawk/.hermit/python/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aat/Projects/pawk/.hermit/python/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 287, in get_requires_for_build_sdist
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/33/k1v9knb976dfb6s0f94qxn080000gn/T/build-env-kayst5ah/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/33/k1v9knb976dfb6s0f94qxn080000gn/T/build-env-kayst5ah/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/33/k1v9knb976dfb6s0f94qxn080000gn/T/build-env-kayst5ah/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'pawk'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```

**Comment by alecthomas** [comment]
I've pushed the code I have up, so maybe someone else can take a look.

**Comment by jrjsmrtn** [comment]
I had a look. I modified your `pyproject.toml` to use Poetry, just to test... and it build successfully:

```sh
$ poetry build --verbose
Using virtualenv: /Users/gm/.virtualenvs/pawk-py37
Building pawk (0.8.0)
  - Building sdist
  - Built pawk-0.8.0.tar.gz
  - Building wheel
  - Built pawk-0.8.0-py3-none-any.whl
```

I had some issues to push and make a PR of my HEAD of your HEAD of v0.8.0, though 😆 so you'll find the diff here: https://github.com/alecthomas/pawk/compare/v0.8.0...jrjsmrtn:pawk:HEAD?expand=1

**Comment by alecthomas** [comment]
Thank you for that, appreciate it! 0.8.0 released
